#!/bin/sh
# Write test/audio/sweep/sweep-<byte>.req: every value of one request byte,
# $00 to $FF in order, twenty ticks apart, over the surface theme ($04). The
# sweep metroid2-audio's Step 15 asks for: `songs/` and `sfx/` grade each id in
# its table, and this grades the rest of the byte's range -- the ids past each
# table, which bank 4 ignores or reads as something else -- and every id
# arriving over whatever the one before it left playing.
#
# Song $10 is left out of the song sweep: its table entry is code rather than
# a header (docs/audio_ids.md). The song byte's own sweep has no song under it.
#
#   tools/gen-sweep-reqs.sh && zig build audiocmp -- test/audio/sweep/*.req
set -eu
cd "$(dirname "$0")/.."
out=test/audio/sweep
mkdir -p "$out"

gap=20

for name in sfxRequest_square1 sfxRequest_square2 sfxRequest_fakeWave \
            sfxRequest_noise sfxRequest_wave songRequest \
            songInterruptionRequest audioPauseControl; do
    {
        echo "# Every value of $name, \$00 to \$FF, $gap ticks apart."
        echo "# GENERATED by tools/gen-sweep-reqs.sh; do not edit."
        if [ "$name" = songRequest ]; then
            echo "[]"
        else
            echo "[songRequest=04]"
        fi
        i=0
        while [ "$i" -lt 256 ]; do
            id=$(printf %02X "$i")
            if [ "$name" = songRequest ] && [ "$id" = 10 ]; then
                echo "[]"
            else
                echo "[$name=$id]"
            fi
            yes '[]' | head -n $((gap - 1))
            i=$((i + 1))
        done
    } > "$out/sweep-$name.req"
done
