#!/bin/sh
# Write test/audio/sfx/: every sound effect id on every channel, each
# requested alone and over the surface theme, the scripts metroid2-audio's
# Steps 13 and 14 grade.
#
#   sq1-XX.req          the effect on the first tick, then three seconds
#   sq1-XX-surface.req  song $04 on the first tick, the effect at tick 60,
#                       four seconds in all, so it lands mid-song and hands
#                       square 1 back to the song when it ends
#   sq2-XX.req, sq2-XX-surface.req      the same for square 2
#   noise-XX.req, noise-XX-surface.req  and the noise channel
#   wave-XX.req, wave-XX-surface.req    and the wave channel's low-health beep
#
# Three seconds covers the longest effect, Samus killed's $B0 ticks. The beep
# does not end by itself, so its three seconds are a run of beeps.
#
# Square 1's $1B and square 2's $03-$06 seed their pitch from rDIV, so each of
# those scripts sets it first, to a value that is not zero.
#
#   tools/gen-sfx-reqs.sh && zig build audiocmp -- test/audio/sfx/*.req
set -eu
cd "$(dirname "$0")/.."
out=test/audio/sfx
mkdir -p "$out"
rm -f "$out"/*.req

# name request id what [extra ops]
gen() {
    name=$1 req=$2 id=$3 what=$4 extra=${5:-}
    {
        echo "# $req \$$id ($what), requested on the first tick, then three seconds."
        echo "# GENERATED by tools/gen-sfx-reqs.sh; do not edit."
        echo "[$extra$req=$id]"
        yes '[]' | head -n 179
    } > "$out/$name-$id.req"
    {
        echo "# $req \$$id ($what) at tick 60, over song \$04 (main caves)."
        echo "# GENERATED by tools/gen-sfx-reqs.sh; do not edit."
        echo "[songRequest=04]"
        yes '[]' | head -n 59
        echo "[$extra$req=$id]"
        yes '[]' | head -n 179
    } > "$out/$name-$id-surface.req"
}

# The divider value the rDIV-seeded ids are run with. Any byte will do; this
# one has both nibbles set and differs from its own swap.
div='rDIV=A7 '

# Square 1's table, in id order from $01 (M2RoS bank_004.asm:2263).
names="jumping hijumping screwAttacking standingTransition crouchingTransition
morphing shootingBeam shootingMissile shootingIceBeam shootingPlasmaBeam
shootingSpazerBeam pickedUpMissileDrop spiderBall pickedUpSmallEnergyDrop
beamDink missileDoorExploding unused11 empty12 bombLaid pipeBugSpawnerStop
select shootingWaveBeam pickedUpLargeEnergyDrop samusHealthChange
noMissileDudShot metroidScrewAttacked metroidCry saved variaSuitTransformation
unpaused"
i=0
for n in $names; do
    i=$((i + 1))
    extra=
    [ "$i" -eq 27 ] && extra=$div   # $1B, the Metroid cry
    gen sq1 sfxRequest_square1 "$(printf %02X "$i")" "$n" "$extra"
done

# Square 2's (M2RoS bank_004.asm:3561).
gen sq2 sfxRequest_square2 01 nothing
gen sq2 sfxRequest_square2 02 nothing
gen sq2 sfxRequest_square2 03 metroidQueenCry "$div"
gen sq2 sfxRequest_square2 04 babyMetroidClearingBlock "$div"
gen sq2 sfxRequest_square2 05 babyMetroidCry "$div"
gen sq2 sfxRequest_square2 06 metroidQueenHurtCry "$div"
gen sq2 sfxRequest_square2 07 automFlamethrower

# The noise channel's (M2RoS bank_004.asm:3715). $05, $09, $0A, $16 and $17
# request a cry on a square channel as well, which reads rDIV.
names="enemyShot enemyKilled projectileExplosion shotBlockDestroyed
metroidHurt samusHurt acidDamage shotMissileDoor metroidQueenCry
metroidQueenHurtCry samusKilled bombDetonated metroidKilled
omegaMetroidExplosion clearedSaveFile footsteps enemyHitGround
projectileFired unused13 gammaMetroidLightning metroidFireball
babyMetroidClearingBlock babyMetroidCry autrackRises unused19 autoadJump"
i=0
for n in $names; do
    i=$((i + 1))
    extra=
    case $i in 5|9|10|22|23) extra=$div ;; esac
    gen noise sfxRequest_noise "$(printf %02X "$i")" "$n" "$extra"
done

# The wave channel's: the low-health beep, one id per ten points of health
# below fifty (M2RoS bank_004.asm:5412).
for i in 1 2 3 4 5; do
    gen wave sfxRequest_wave "0$i" "health under $((i * 10))"
done
