#!/bin/sh
# Write test/audio/songs/song-XX.req: one per song id that extracts, each the
# song requested on the first tick and then sixty seconds of ticks (3600 at
# one a frame), the window metroid2-audio's Step 12 grades every song over.
#
# $10 is left out: bank 4's table points it at `initializeAudio.ret`, code
# rather than a header, so there is no song to extract (docs/audio_ids.md).
#
#   tools/gen-song-reqs.sh && zig build audiocmp -- test/audio/songs/*.req
set -eu
cd "$(dirname "$0")/.."
out=test/audio/songs
mkdir -p "$out"

# The song table's names, in id order from $01 (M2RoS bank_004.asm).
names="babyMetroid metroidQueenBattle chozoRuins mainCaves subCaves1 subCaves2
subCaves3 finalCaves metroidHive itemGet metroidQueenHallway metroidBattle
subCaves4 earthquake killedMetroid nothing title samusFanfare reachedTheGunship
chozoRuins_clone mainCaves_noIntro subCaves1_noIntro subCaves2_noIntro
subCaves3_noIntro finalCaves_clone metroidHive_clone itemGet_clone
metroidQueenHallway_clone metroidBattle_clone subCaves4_noIntro
metroidHive_withIntro missilePickup"

i=0
for name in $names; do
    i=$((i + 1))
    [ "$i" -eq 16 ] && continue
    id=$(printf %02X "$i")
    {
        echo "# Song \$$id ($name), requested on the first tick, then sixty seconds."
        echo "# GENERATED by tools/gen-song-reqs.sh; do not edit."
        echo "[songRequest=$id]"
        yes '[]' | head -n 3600
    } > "$out/song-$id.req"
done
