//! 1.0 Step 22c: the `credits` rung -- the ending graded against our Game Boy.
//!
//! One Mesen2 run a clock (`credits.variants`): each side of the three hours
//! `credits_animateSamus` tests. The `--debug` cart is a new game set up
//! through the menu's own input -- the clock on CLOCK; for the first variant
//! every METROIDS row killed, the Queen's last, then the missile refill at
//! `$F:$76` touched; for the rest the WARP page's ENDING -- and our Game Boy
//! takes the refill's lever with the same clock (`credits.reference`).
//!
//! Graded at the top of every pass, on what the pass before left
//! (`credits.zig` says where each machine is read):
//! - the fade, the palette pass for pass, and its length;
//! - the characters the setup leaves, objects and background;
//! - the scroll, the animation state, the done flag and the objects' hash,
//!   pass for pass, from the first credits pass to the hold's end;
//! - the whole tilemap and the objects in full on a few passes;
//! - the end: the hold's passes unchanged but for the state's own animation,
//!   then A, B, Start and Select reboot to the title, as on the Game Boy.
//!
//! The cart's frame counter at the first credits pass is the route's, pinned
//! in `credits.variants`; our Game Boy's is set to it there.

const std = @import("std");
const credits = @import("credits.zig");
const warp = @import("warp.zig");
const warp_grade = @import("warp_grade.zig");
const debug_tables = @import("debug_tables.zig");
const target = @import("snes_target.zig");
const screen = @import("snes_screen.zig");

const sym = warp_grade.sym;

pub fn code(c: u8) []const u8 {
    return switch (c) {
        0 => "held",
        50 => "the cart's frame counter at the first credits pass is not the one `credits.variants` pins",
        51 => "the fade's palette differs from our Game Boy's on a pass",
        52 => "the fade is not our Game Boy's length",
        53 => "the characters the setup leaves are not our Game Boy's",
        54 => "the scroll differs from our Game Boy's on a pass",
        55 => "Samus's animation state differs from our Game Boy's on a pass",
        56 => "the scroll's done flag differs from our Game Boy's on a pass",
        57 => "the objects differ from our Game Boy's on a pass",
        58 => "the tilemap differs from our Game Boy's on a sampled pass",
        60 => "A, B, Start and Select held did not reboot to the title",
        61 => "the missile refill was never touched",
        else => warp_grade.scenarioCode(c),
    };
}

/// The mode $13 passes the whole tilemap and the objects are graded on, as
/// well as the three `credits.reference` takes of itself: the scroll's end,
/// the ending settling, and the hold's last.
pub const sample_passes = [_]u32{ 0, 1, 2000 };

/// The rung's faults, each a patch at an engine label on one variant's cart,
/// and the exit it must make.
pub const Fault = struct { label: []const u8, patch: []const u8, variant: usize, want: u8, what: []const u8 };
pub const faults = [_]Fault{
    .{ .label = "PrepareCredits_fadeIndex", .patch = &.{ 0x29, 0x07, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA }, .variant = 1, .want = 51, .what = "the fade's index from the countdown's low bits" },
    .{ .label = "CreditsScroll_rate", .patch = &.{ 0x29, 0x01 }, .variant = 1, .want = 54, .what = "a pixel every second frame" },
    .{ .label = "CreditsStates_bestHours", .patch = &.{ 0xC9, 0x04 }, .variant = 1, .want = 55, .what = "the best ending's `CP $03` made $04" },
    .{ .label = "SoftReset_mask", .patch = &.{ 0xC9, 0xFF, 0xFF }, .variant = 5, .want = 60, .what = "the soft reset's mask matching nothing" },
};

pub fn writeLua(a: std.mem.Allocator, rom: []const u8, sorted: []const warp.Entry, mets: []const u8, v: credits.Variant, r: credits.Reference, w: *std.Io.Writer) !void {
    _ = a;
    try w.print(
        \\-- Generated by `zig build verify`. Do not edit.
        \\--
        \\-- The `credits` rung's {s} (1.0 Step 22c, `src/credits_grade.zig`): the
        \\-- `--debug` cart set up through the menu's own input, its ending graded
        \\-- pass for pass against our Game Boy's from the refill's lever.
        \\--
        \\-- Exit codes: 0 held; 1 Fatal; 2 out of frames; 3 A did not warp; 4 an
        \\-- unrunnable pose; 50 the frame counter's phase moved (re-pin it);
        \\-- 51 the fade's palette; 52 its length; 53 the characters; 54 the
        \\-- scroll; 55 the state; 56 the done flag; 57 the objects; 58 the
        \\-- tilemap; 60 the soft reset; 61 no touch.
        \\
    , .{v.name});
    try warp_grade.writeMenuPrelude(rom, sorted, 14000, w);

    const ending_row = blk: {
        var n: usize = 0;
        for (sorted, 0..) |_, i| n += @intFromBool(debug_tables.warpRow(sorted, i)[0] == debug_tables.ending_list);
        break :blk n;
    };
    try w.print(
        \\local VR = emu.memType.snesVideoRam
        \\local C = {{ mode = {d}, pal = {d}, scroll = {d}, state = {d}, done = {d}, oamidx = {d}, oam = {d},
        \\  stage = {d}, x = {d} }}
        \\local CREDITS_FRAME, REBOOT, TITLE_FRAME = {d}, {d}, {d}
        \\local HOURS, MINUTES, ROUTE, PHASE = {d}, {d}, "{s}", {d}
        \\local CLOCK_ROW, METROIDS_ROW, METS_N, ENDING_ROW, COLLECT_ROW = {d}, {d}, {d}, {d}, {d}
        \\local MISSILE, RESET_FRAMES, MISS_ROW, SAMUS_N = {d}, {d}, {d}, {d}
        \\local BAND_TOP, WIN_LEFT, OBJ_BYTE, BG3_MAP_BYTE = {d}, {d}, {d}, {d}
        \\
    , .{
        try sym("VarDeathMode"),             try sym("VarBgPalette"),
        try sym("VarCrScrollY"),             try sym("VarCrState"),
        try sym("VarCrDone"),                try sym("VarOamIdx"),
        try sym("VarOamBuf"),                try sym("VarItemStage"),
        try sym("VarOnscreenX"),             try sym("CreditsFrame"),
        try sym("Reboot"),                   try sym("TitleFrame"),
        v.hours,                             v.minutes,
        @tagName(v.route),                   v.phase,
        @intFromEnum(@import("scenario.zig").Page.clock), warp_grade.metroids_row,
        mets[0],                             ending_row,
        try warp_grade.collectRow(sorted),   @import("items.zig").sprite_missile_refill,
        credits.reset_frames,                @intFromEnum(@import("scenario.zig").Row.missiles),
        @typeInfo(@import("scenario.zig").Row).@"enum".fields.len, screen.band_top,
        screen.win_left,                     @as(u32, target.obj_char_base) * 2,
        @as(u32, target.bg3_map_base) * 2,
    });

    // The reference.
    try w.print("FADE = {{", .{});
    for (r.fade) |p| try w.print("{d},", .{p});
    try w.print("}}\nSCROLL, STATE, DONE, OBJS, HASH = {{}}, {{}}, {{}}, {{}}, {{}}\n", .{});
    // Passes in chunks, so no one line is a megabyte.
    var i: usize = 0;
    while (i < r.passes.len) : (i += 256) {
        const end = @min(i + 256, r.passes.len);
        try w.print("for i, p in ipairs({{", .{});
        for (r.passes[i..end]) |p| try w.print("{{{d},{d},{d},{d},{d}}},", .{ p.scroll, p.state, p.done, p.objects, p.hash });
        try w.print("}}) do SCROLL[{d} + i], STATE[{d} + i], DONE[{d} + i], OBJS[{d} + i], HASH[{d} + i] = p[1], p[2], p[3], p[4], p[5] end\n", .{ i, i, i, i, i });
    }
    try w.print("SAMPLE = {{}}\n", .{});
    for (r.samples) |s| {
        try w.print("SAMPLE[{d}] = {{ objects = {d}, map = {{", .{ s.pass + 1, s.objects });
        for (s.map) |b| try w.print("{d},", .{b});
        try w.print("}}, oam = {{", .{});
        for (s.oam[0 .. @as(usize, @min(s.objects, credits.oam_max)) * 4]) |b| try w.print("{d},", .{b});
        try w.print("}} }}\n", .{});
    }
    try w.print("OBJ_CHR = {{", .{});
    for (r.obj_chr) |b| try w.print("{d},", .{b});
    try w.print("}}\nBG_CHR = {{", .{});
    for (credits.bg_spans, r.bg_chr) |sp, c| {
        // The Game Boy id at `at` under the signed window.
        const id: u8 = if (sp.at >= 0x9000) @intCast((sp.at - 0x9000) / 16) else @intCast((sp.at - 0x8800) / 16 + 0x80);
        try w.print("{{ id = {d}, bytes = {{", .{id});
        for (c[0..sp.len]) |b| try w.print("{d},", .{b});
        try w.print("}} }},", .{});
    }
    try w.print("}}\nRESET_GB, HOLD = {d}, {d}\n", .{ r.reset, r.hold });

    try w.print(
        \\
        \\-- The cart's objects as the Game Boy's: `PutObject` (00:$B... ) undone.
        \\local function gbAttr(a)
        \\  local g = 0
        \\  if a & 0x80 ~= 0 then g = g | 0x40 end
        \\  if a & 0x40 ~= 0 then g = g | 0x20 end
        \\  if (a >> 1) & 7 == 1 then g = g | 0x10 end
        \\  if (a >> 4) & 3 == 0 then g = g | 0x80 end
        \\  return g
        \\end
        \\local function cartObjects()
        \\  local n = rd16(C.oamidx) // 4
        \\  local out = {{}}
        \\  -- The forty the Game Boy's buffer holds: it draws on past them unseen.
        \\  for i = 0, math.min(n, 40) - 1 do
        \\    local b = C.oam + i * 4
        \\    local hi = (emu.read(C.oam + 512 + (i >> 2), wram) >> ((i & 3) * 2)) & 1
        \\    local x = ((hi << 8) | emu.read(b, wram)) - WIN_LEFT + 8
        \\    local y = emu.read(b + 1, wram) - BAND_TOP + 16
        \\    out[#out + 1] = y & 0xFF
        \\    out[#out + 1] = x & 0xFF
        \\    out[#out + 1] = emu.read(b + 2, wram)
        \\    out[#out + 1] = gbAttr(emu.read(b + 3, wram))
        \\  end
        \\  return n, out
        \\end
        \\local function hash(t)
        \\  local h = 0
        \\  for _, b in ipairs(t) do h = (h * 31 + b) & 0xFFFFFFFF end
        \\  return h
        \\end
        \\
        \\local p12, q, held, rebooted, titled = 0, 0, false, false, false
        \\emu.addMemoryCallback(function()
        \\  if stopped then return end
        \\  local mode = emu.read(C.mode, wram)
        \\  if mode == 0x12 then
        \\    if p12 > 0 and emu.read(C.pal, wram) ~= FADE[p12] then
        \\      fail(51, string.format("fade pass %d: palette %02x, our Game Boy's %02x", p12, emu.read(C.pal, wram), FADE[p12]))
        \\    end
        \\    p12 = p12 + 1
        \\    return
        \\  end
        \\  if mode ~= 0x13 then return end
        \\  if q == 0 then
        \\    if p12 ~= #FADE then fail(52, string.format("the fade took %d passes, our Game Boy's %d", p12, #FADE)) end
        \\    if emu.read(C.pal, wram) ~= FADE[#FADE] then fail(51, "the setup's palette " .. emu.read(C.pal, wram)) end
        \\    if emu.read(0, wram) ~= PHASE then
        \\      fail(50, string.format("frame counter %d at the first credits pass; `credits.variants` pins %d", emu.read(0, wram), PHASE))
        \\    end
        \\    for t = 0, 255 do
        \\      for k = 0, 15 do
        \\        local got, want = emu.read(OBJ_BYTE + t * 32 + k, VR), OBJ_CHR[t * 16 + k + 1]
        \\        if got ~= want then fail(53, string.format("object character %02x byte %d: %02x, our Game Boy's %02x", t, k, got, want)); return end
        \\      end
        \\    end
        \\    for _, s in ipairs(BG_CHR) do
        \\      for k = 0, #s.bytes - 1 do
        \\        local c = (s.id + (k // 16) + 0x80) & 0xFF
        \\        local got = emu.read(c * 16 + k % 16, VR)
        \\        if got ~= s.bytes[k + 1] then
        \\          fail(53, string.format("background id %02x byte %d: %02x, our Game Boy's %02x", s.id + k // 16, k % 16, got, s.bytes[k + 1]))
        \\          return
        \\        end
        \\      end
        \\    end
        \\  else
        \\    -- Past the hold the reset is under way, and the passes it takes are
        \\    -- the machine's own: graded by the reset's frames, not here.
        \\    if q - 1 > HOLD then q = q + 1; return end
        \\    local n, objs = cartObjects()
        \\    local s, st, d = emu.read(C.scroll, wram), emu.read(C.state, wram), emu.read(C.done, wram)
        \\    if s ~= SCROLL[q] then fail(54, string.format("pass %d: scroll %d, our Game Boy's %d", q - 1, s, SCROLL[q])) end
        \\    if st ~= STATE[q] then fail(55, string.format("pass %d: state %02x, our Game Boy's %02x", q - 1, st, STATE[q])) end
        \\    if d ~= DONE[q] then fail(56, string.format("pass %d: done %d, our Game Boy's %d", q - 1, d, DONE[q])) end
        \\    local smp = SAMPLE[q]
        \\    if smp ~= nil then
        \\      for k = 0, 1023 do
        \\        local id = (emu.read(BG3_MAP_BYTE + k * 2, VR) - 0x80) & 0xFF
        \\        if id ~= smp.map[k + 1] then
        \\          fail(58, string.format("pass %d: tilemap row %d column %d id %02x, our Game Boy's %02x", q - 1, k // 32, k % 32, id, smp.map[k + 1]))
        \\          return
        \\        end
        \\      end
        \\      for k = 1, #smp.oam do
        \\        if objs[k] ~= smp.oam[k] then
        \\          fail(57, string.format("pass %d: object %d byte %d: %d, our Game Boy's %d", q - 1, (k - 1) // 4, (k - 1) % 4, objs[k] or -1, smp.oam[k]))
        \\          return
        \\        end
        \\      end
        \\    end
        \\    if n ~= OBJS[q] or hash(objs) ~= HASH[q] then
        \\      fail(57, string.format("pass %d: %d objects, hash %08x; our Game Boy's %d, %08x; first (%d,%d,%02x,%02x)", q - 1, n,
        \\        hash(objs), OBJS[q], HASH[q], objs[1] or -1, objs[2] or -1, objs[3] or -1, objs[4] or -1))
        \\    end
        \\    if q - 1 == HOLD then held = true end
        \\  end
        \\  q = q + 1
        \\end, emu.callbackType.exec, CREDITS_FRAME)
        \\emu.addMemoryCallback(function() rebooted = true end, emu.callbackType.exec, REBOOT)
        \\emu.addMemoryCallback(function() if rebooted then titled = true end end, emu.callbackType.exec, TITLE_FRAME)
        \\
        \\-- The clock, on CLOCK: hours up from the new game's 0:00, then 59
        \\-- minutes as one press left.
        \\local function clock()
        \\  page(CLOCK_ROW)
        \\  for i = 1, (HOURS >> 4) * 10 + (HOURS & 15) do press("right") end
        \\  press("down")
        \\  if MINUTES == 0x59 then press("left") end
        \\  press("b"); press("b")
        \\end
        \\-- The missile refill sits above the floor she is put on: she jumps
        \\-- towards it until the pickup starts (as the `warp` rung's touch).
        \\local function touch()
        \\  for i = 1, 180 do
        \\    local x
        \\    for s = 0, SLOTS - 1 do
        \\      local b = R.slots + s * SLOT_SIZE
        \\      if emu.read(b, wram) ~= EMPTY and emu.read(b + 3, wram) == MISSILE then x = emu.read(b + 2, wram) end
        \\    end
        \\    if x == nil then fail(61, "no missile refill in a slot") end
        \\    local me = emu.read(C.x, wram)
        \\    PAD = {{ b = (i % 40 < 30), left = (x < me - 2), right = (x > me + 2) }}
        \\    frame()
        \\    if emu.read(C.stage, wram) ~= 0 then PAD = {{}}; return end
        \\  end
        \\  PAD = {{}}
        \\  fail(61, "jumped for 180 frames towards the missile refill: no pickup")
        \\end
        \\local function main()
        \\  clock()
        \\  if ROUTE == "refill" then
        \\    -- Every row of METROIDS killed, the Queen's last, as the `warp`
        \\    -- rung's `refill_credits`; then the refill at $F:$76.
        \\    -- Warped there first, at the new game's count, as `refill_credits`:
        \\    -- the count moves the lava, and the room at zero is another.
        \\    loadout()
        \\    warp(1, COLLECT_ROW); wait(10)
        \\    page(METROIDS_ROW)
        \\    for r = 1, METS_N - 1 do press("right"); press("down") end
        \\    press("a")
        \\    press("b"); press("b"); wait(10)
        \\    if emu.read(R.real, wram) ~= 0 then fail(61, "the count is not zero") end
        \\    -- Ten missiles fewer on SAMUS: the orb takes no touch with them full.
        \\    page(0); rows(0, MISS_ROW, SAMUS_N); press("left"); press("b"); press("b")
        \\    touch()
        \\  else
        \\    warp(3, ENDING_ROW)
        \\  end
        \\  while not held do frame() end
        \\  PAD = {{ b = true, y = true, start = true, select = true }}
        \\  for i = 1, RESET_FRAMES do
        \\    frame()
        \\    if rebooted then break end
        \\  end
        \\  PAD = {{}}
        \\  if not rebooted then fail(60, string.format("held %d frames: no reboot (our Game Boy's took %d)", RESET_FRAMES, RESET_GB)) end
        \\  for i = 1, 300 do
        \\    if titled then break end
        \\    frame()
        \\  end
        \\  if not titled then fail(60, "rebooted, and the title never ran") end
        \\  print(string.format("{s}: the fade %d passes, %d credits passes, the end held, and the reset reached the title", #FADE, #SCROLL))
        \\  emu.stop(0)
        \\end
        \\
    , .{v.name});
    try warp_grade.writeRunner(w);
}
